# Generated by Django 4.2.16 on 2024-10-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerInfo',
            fields=[
                ('job_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用户名称')),
                ('department', models.CharField(default='', max_length=200, verbose_name='所在部门')),
            ],
            options={
                'verbose_name': '借用人',
                'verbose_name_plural': '借用人管理',
                'db_table': 't_borrower_info',
            },
        ),
        migrations.CreateModel(
            name='HuaweiDevice',
            fields=[
                ('imei_sn', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='设备唯一标识符')),
                ('model_name', models.CharField(default='', max_length=100, verbose_name='设备名称')),
                ('model_num', models.CharField(default='', max_length=100, verbose_name='设备编号')),
                ('color', models.CharField(default='', max_length=50, verbose_name='设备颜色')),
                ('status', models.IntegerField(choices=[(0, 'In Stock'), (2, 'Borrowed'), (1, 'Returned'), (3, 'Out of Stock')], default=0, verbose_name='设备状态')),
            ],
            options={
                'verbose_name': '华为设备',
                'verbose_name_plural': '华为设备列表',
                'db_table': 't_huawei_devices',
            },
        ),
        migrations.CreateModel(
            name='StockOutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_time', models.DateTimeField(auto_now_add=True)),
                ('stock_out_person', models.CharField(max_length=100)),
                ('stock_Remark', models.CharField(default='', max_length=200, verbose_name='设备备注')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesManager.huaweidevice')),
            ],
            options={
                'db_table': 't_stock_out_info',
            },
        ),
        migrations.CreateModel(
            name='StockInInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_time', models.DateTimeField(auto_now_add=True)),
                ('stock_in_person', models.CharField(max_length=100)),
                ('stock_Remark', models.CharField(default='', max_length=200, verbose_name='设备备注')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesManager.huaweidevice')),
            ],
            options={
                'db_table': 't_stock_in_info',
            },
        ),
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateTimeField(auto_now_add=True)),
                ('borrow_days', models.PositiveIntegerField()),
                ('borrow_reason', models.TextField(blank=True)),
                ('back_time', models.DateTimeField(blank=True, null=True)),
                ('borrow_operator', models.CharField(default='', max_length=100, verbose_name='操作人')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_info', to='DevicesManager.borrowerinfo')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='设备信息', to='DevicesManager.huaweidevice')),
            ],
            options={
                'db_table': 't_borrow_info',
            },
        ),
    ]
