# Generated by Django 4.2.16 on 2024-10-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinfo',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesManager.borrowerinfo', verbose_name='关联借机信息'),
        ),
        migrations.AlterField(
            model_name='borrowinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesManager.huaweidevice', verbose_name='关联设备'),
        ),
    ]
