# Generated by Django 5.1.4 on 2024-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessions',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('token', 'Token')], default='password', max_length=20, verbose_name='登录方式'),
        ),
    ]
