# Generated by Django 5.1.4 on 2024-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomManager', '0002_usersessions_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthlogs',
            name='failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='失败原因'),
        ),
    ]
