# Generated by Django 5.1.4 on 2024-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomManager', '0002_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=50, unique=True)),
                ('current_value', models.PositiveIntegerField(default=1000000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('login_id', 'login_type')},
        ),
    ]
