# Generated by Django 5.1.4 on 2024-12-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomManager', '0003_useridcounter_alter_userprofile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthlogs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomManager.userprofile', verbose_name='用户唯一标识符'),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomManager.userprofile', verbose_name='用户唯一标识符'),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomManager.userprofile', verbose_name='用户唯一标识符'),
        ),
    ]
