# Generated by Django 5.1.4 on 2024-12-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomManager', '0003_userauthlogs_failure_reason'),
        ('CustomManager', '0004_alter_userauthlogs_user_id_and_more'),
    ]

    operations = [
    ]
